export const UPDATE_SELECTED_STATE = "UPDATE_STATE";
export const UPDATE_SELECTED_DISTRICT = "UPDATE_DISTRICT";
export const UPDATE_SELECTED_SUBDISTRICT = "UPDATE_SUBDISTRICT";
export const UPDATE_SELECTED_VILLAGE = "UPDATE_VILLAGE";
export const UPDATE_SELECTED_POSTOFFICE = "UPDATE_POSTOFFICE";
export const RESET_PINCODE_DETAILS = "RESET_PINCODE_DETAILS";
